import './index.sass'

export { default as Advert } from './advert_list'
export { default as Banner } from './banner'
export { default as Tab } from './tabs/index'
export { default as EntryTab } from './tabs/entryTab'
export { default as NormalList } from './normalList'
export { default as RowList } from './rowList'
export { default as OperationList } from './operationList'
export { default as NewList } from './newList'
export { default as CutList } from './cutList'
export { default as GridList } from './gridList'
export { default as GridList2 } from './gridList2'
export { default as Title } from './title'
export { default as Quote } from './quote'
export { default as Paragraph } from './paragraph'
export { default as ComImg } from './com_img'
export { default as ComButton } from './com_button'
export { default as ComFAQ } from './com_faq'
export { default as ComFooter } from './com_footer'
export { default as ComStep } from './com_step'
// 轮播图
export { default as Carousel } from './carousel'